= Installasjon av programvare for arbeid med UML-modeller i  SOSI-modellregister
Standardiseringssekretariatet <standardiseringssekretariatet@kartverket.no>
Versjon 3.0

:imagesdir: img/
:sectnums:
:docinfo:
:icons: font
:lang: no

//Versjon 3.0alfa
 
//Denne veilederen erstatter installasjonveileder for EA 15 og tidligere, som kan finnes på stien: https://sosi.geonorge.no/veiledere/installasjonsveileder

== Introduksjon

For å jobbe med UML-modeller i SOSI-modellregister må man ha installert en del programvare.
Her kan du finne lenker til alle verktøyene som trengs. Andre veiledere kan finnes på https://www.geonorge.no/verktoy/verktoy-for-produktspesifikasjon/[sidene for verktøy og veiledere på geonorge.no].

== Installasjon av Enterprise Architect 

For å jobbe med UML-modeller trenger du Enterprise Architect (EA).  +
Vi anbefaler å installere 64-bits utgaven av EA versjon 16. + 
Se xref:installasjonAvEA.adoc[veileder for installasjon av EA 16].


== Tilgang til SOSI-modellregister

Vi anbefaler å https://sosi.geonorge.no/modellfiler/sosi_modellregister.qea[laste ned en oppdatert prosjektfil (sosi_modellregister.qea)]. Denne fila inneholder hele modellregisteret. Modellene der kan leses og brukes direkte. Fila inneholder også SOSI-UML profil 5.1 og verktøy for å dokumentere modellen.

Hvis du skal oppdatere modeller i SOSI-modellregister, må du  xref:tilgangtilmodellregisteret.adoc[installere og konfigurere SVN].

xref:konfigurereTilgangFraEAtilSVN.adoc[Du må deretter sette opp versjonskontroll i EA].

== Installasjon av tilleggsfunksjoner til EA

For å installere tilleggene må du sørge for at EA er lukket.

=== SOSI Model Validation Add-In
SOSI Model Validation er et tillegg til EA, utviklet av Kartverket, som hjelper deg å sjekke om modellen din er i henhold til krav og anbefalinger i standarden https://register.geonorge.no/standarder/sosi/del-1-generell-del/regler-for-uml-modellering[Regler for UML-modellering (register.geonorge.no)]. +

https://register.geonorge.no/filer/uml-verkt%C3%B8y/sosi-model-validation-64-bit[SOSI model validation lastes ned fra register.geonorge.no]

=== ShapeChange Add-In for EA
ShapeChange brukes til å generere GML-skjemaer fra UML-modeller.

https://register.geonorge.no/filer/uml-verkt%C3%B8y/shapechange-add-in-64-bit[ShapeChange Add-In lastes ned fra register.geonorge.no]

=== SOSI plugin i EA

Hensikten med dette tillegget er å generere definisjonsfiler for SOSI-kontroll. Dette kan være aktuelt desom produktspesifikasjonene skal realisers i SOSI-format.

https://register.geonorge.no/filer/uml-verkt%C3%B8y/sosi-plugin-64-bit[SOSI plugin i EA lastes ned fra register.geonorge.no]

== Verktøy for dokumentasjon av modellene

Dokumentasjon av modellene kan lages med et innebygget EA-skript. Skript følger med den ferdigkonfigurerte prosjektfila for modellregisteret, men kan også lastes ned fra github.

Skriptet genererer modelldokumentasjon i AsciiDoc-format.

For installasjon og bruk av AsciiDoc og AsciiDoctor, se xref:https://www.geonorge.no/globalassets/geonorge2/standardisering/veiledere/asciidocveileder.html[veileder for bruk av Asciidoc]





































